# Generated by Django 5.0.7 on 2024-07-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_user_email'),
    ]

    operations = [
    ]
