# Generated by Django 5.0.7 on 2024-08-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_id', models.IntegerField()),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_pay', models.DateField()),
                ('for_month', models.CharField(max_length=7)),
                ('transaction_mode', models.CharField(max_length=50)),
            ],
        ),
    ]
