# Generated by Django 5.0.7 on 2024-08-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_payment', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='owner_id',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='renter',
            new_name='renter_id',
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
