# Generated by Django 5.0.7 on 2024-08-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_payment', '0003_rename_owner_id_lease_address_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
