# Generated by Django 5.0.7 on 2024-08-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_payment', '0004_alter_lease_end_date_alter_lease_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_of_pay',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_mode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
