# Generated by Django 5.0.7 on 2024-08-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_payment', '0005_alter_payment_date_of_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
