# Generated by Django 5.0.7 on 2024-08-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_payment', '0006_alter_payment_transaction_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_remain_pay',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
