# Generated by Django 5.0.7 on 2024-08-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_payment', '0007_payment_is_remain_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='for_month',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
