# Generated by Django 5.0.7 on 2024-08-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease_payment', '0008_alter_payment_for_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='for_month',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
