# Generated by Django 5.0.7 on 2024-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='owner_id',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
