# Generated by Django 5.0.7 on 2024-07-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_on_rent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
