# Generated by Django 5.0.7 on 2024-07-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(null=True)),
                ('renter_name', models.CharField(max_length=60)),
                ('renter_mobile_no', models.IntegerField()),
                ('id_type', models.CharField(max_length=30)),
                ('id_img', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
