# Generated by Django 5.0.7 on 2024-07-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='owner_id',
            field=models.IntegerField(),
        ),
    ]
