# Generated by Django 5.0.7 on 2024-08-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_alter_renter_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renter',
            name='renter_mobile_no',
            field=models.CharField(max_length=20),
        ),
    ]
